# Configurable settings
[[config]]
    name = "order-size"
    label = "Order Size"
    type = "price"
[[config]]
    name = "stop-offset"
    label = "Stop Distance"
    type = "percent"
    default = 5
[[config]]
    name = "tp-distances"
    label = "Take Profit Distances"
    type = "list"
    [[config.list-value]]
        label = "TP 1"
        type = "percent"
        default = 1
    [[config.list-value]]
        label = "TP 2"
        type = "percent"
        default = 5
    [[config.list-value]]
        label = "TP 3"
        type = "percent"
        default = 10

# Input signals
[inputs]
    enter-long = {type = "event"}
    enter-short = {type = "event"}
    market-close = {type = "event"}

# Strategy logic
[states]
    initial = "not-in-position"

    # When not in a position:
    [[states.state]]
        id = "not-in-position"

        [[states.state.orders]]
            # Only place this order when entering long
            when = "=> inputs.enter-long and account.position < 0"
            # Every order needs a unique tag
            tag = "close short"
            # Order properties
            type = "market"
            side = "buy"
            contracts = "=> [Math.abs: account.position]"

        [[states.state.orders]]
            # Only place this order when entering long
            when = "=> inputs.enter-long"
            # Every order needs a unique tag
            tag = "long"
            # Order properties
            type = "market"
            side = "buy"
            contracts = "=> config.order-size"
            # When this order has filled, switch to the "in-position" state
            on.fill.data.stop-base-price = "=> event.order.fill-price"
            on.fill.to-state = "in-position"
        
        [[states.state.orders]]
            # Only place this order when entering short
            when = "=> inputs.enter-short and account.position > 0"
            # Every order needs a unique tag
            tag = "close long"
            # Order properties
            type = "market"
            side = "sell"
            contracts = "=> [Math.abs: account.position]"

        [[states.state.orders]]
            # Only place this order when entering short
            when = "=> inputs.enter-short"
            # Every order needs a unique tag
            tag = "short"
            # Order properties
            type = "market"
            side = "sell"
            contracts = "=> config.order-size"
            # When this order has filled, switch to the "in-position" state
            on.fill.data.stop-base-price = "=> event.order.fill-price"
            on.fill.to-state = "in-position"
    
    # When in a position:
    [[states.state]]
        id = "in-position"

        data.exit-direction = "=> account.position > 0 ? 'sell' : 'buy'"

        # Set state back to "not-in-position" when position is closed
        # Note that TP orders have an 'on.fill' trigger that only adds a note, this will cause this trigger to be checked when a TP fills
        [[states.state.trigger]]
            when = "=> account.position == 0"
            to-state = "not-in-position"

        # Place stop loss
        [[states.state.orders]]
            tag = "stop-loss"
            type = "stop-market"
            side = "=> #exit-direction"
            contracts = "=> [Math.abs: account.position]"
            trigger-price = "=> #stop-base-price - [Trades.position-side: config.stop-offset]"
            instructions = ['close']
            on.trigger.note = "Stop Triggered"
            on.trigger.to-state = "not-in-position"
        
        # Place take profit limit orders, each for half of the position
        [[states.state.orders]]
            # Use the first number-of-tp-orders values from the list of tp-distances
            foreach.tp = "=> config.tp-distances"
            tag = "tp/#tp"
            type = "limit"
            side = "=> #exit-direction"
            contracts = "=> [Math.truncate: config.order-size / 3]"
            price = "=> [Trades.price-offset: #tp, account.avg-price]"
            instructions = ['reduce-only', 'post-only']
            on.fill.data.stop-base-price = "=> event.order.fill-price"

        # Close position on exit signal
        [[states.state.orders]]
            when = "=> inputs.market-close"
            tag = "exit"
            type = "market"
            side = "=> #exit-direction"
            contracts = "=> account.position"
            instructions = ['close']
            on.fill.to-state = "not-in-position"
