name = "Test Strategy"
description = "Strategy to test the dawn scripting engine"

[[config]]
    name = "conf1"
    label = "Config 1"
    type = "number"
    default = 0
[[config]]
    name = "conf2"
    label = "Config 2"
    type = "number"
    default = 0
[[config]]
    name = "ma-src"
    label = "Moving Average Source"
    type = "signal"
    default = "signals.ema"

[inputs]
    in1 = { type = "number" }
    in2 = { type = "number" }
    sig1 = { type = "signal", source = "config.ma-src" }

[data]
    a = 0
    counter = 0

[functions]
    [functions.sma]
        params = {x = "number"}
        formula = "=> #x "
        action.to-state = "=> #result"

[states]
    initial = "start"

    [[states.state]]
        id = "start"

        [[states.state.trigger]]
            when = "=> #counter < 2"
            data.counter = "=> #counter + 1"
            note.text = "=> [text: 'Counter = ', #counter]"
            to-state = "next"
    
    [[states.state]]
        id = "next"
        note.text = "=> #counter"

        [[states.state.trigger]]
            when = "=> #counter == 0"
            to-state = "end"

        [[states.state.trigger]]
            when = true
            data.counter = "=> #counter - 1"
            note.text = "=> #counter"


        [[states.state.orders]]
            tag         = "order"
            type        = "market"
            side        = "buy"
            contracts   = 100
            on.fill.note.text = "Filled"

    [[states.state]]
        id = "end"
        note.text = "END"

        [[states.state.trigger]]
            when = "=> #counter > inputs.in2"
            note.text = "Greater than in2"
